<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Modules.Stuff.Application\Modules.Stuff.Application.csproj" />
		<ProjectReference Include="..\Modules.Stuff.Domain\Modules.Stuff.Domain.csproj" />
	</ItemGroup>
</Project>