<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
	  <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.9" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Modules.Matches.Domain\Modules.Matches.Domain.csproj" />
		<ProjectReference Include="..\Modules.Matches.Infrastructure\Modules.Matches.Infrastructure.csproj" />
		<ProjectReference Include="..\Modules.Matches.Ui\Modules.Matches.Ui.csproj" />
		<ProjectReference Include="..\Modules.Staff.Ui\Modules.Stuff.Ui.csproj" />
		<ProjectReference Include="..\Modules.Teams.Application\Modules.Teams.Application.csproj" />
	</ItemGroup>

</Project>